/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "P2_0_aliases.h"
#include "P2_0.h"
#include "P2_1_aliases.h"
#include "P2_1.h"
#include "P2_2_aliases.h"
#include "P2_2.h"
#include "P2_3_aliases.h"
#include "P2_3.h"
#include "P2_4_aliases.h"
#include "P2_4.h"
#include "P2_5_aliases.h"
#include "P2_5.h"
#include "P2_6_aliases.h"
#include "P2_6.h"
#include "P2_7_aliases.h"
#include "P2_7.h"
#include "Timer_1.h"
#include "Clock_1.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

